# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://jsh8w.github.io/
baseurl:
title: James Shaw | iOS Developer | iPhone, iPad, Apple Watch and Apple TV
author: James Shaw
description: Personal blog and CV
avatar: profile.png
github: jsh8w
twitter: jsh8w
linkedin: shawjames
stackoverflow: users/5032154/jsh8w

# needed for travis-ci build
exclude: [vendor]
